### ISSUE TITLE
How do we prioritize "In Progress" items?

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/sig-contributor-experience#15]
We can’t do and talk about all the issues at once. How do we figure out what to focus on? How do we prioritize next steps?

**Comment by tedsuo** [comment]
We definitely should only work on projects where we feel like we have the right people and resources available to succeed. 

But, I also feel that it is important that we coordinate and work together on a smaller number of issues, rather than split our energy up across a bunch of different issues. Taking on too many projects at once is a common failure mode for Otel. When that happens, every project moves slowly and struggles to get reviews and quick feedback.  So there still needs to be some way that we as a group decide which three or four things we're going to tackle first, before moving on the next set of things. Especially at the beginning, when we are going to have more ideas than we have bandwidth.

👍 is a useful way of gauging interest. But maybe the rule should be that you only thumbs up issues that you're _willing to work on_, as opposed to just what you think is important.

**Comment by svrnm** [comment]
Proposal:

* every contributor from the SIG picks 2 topics (max!) they want to work on, they assign the issue to themselves
* if an issue has 3+ assignees, it will be worked on
* if an issue is to broad in scope, step 1 is breaking down the issue into sub-tasks
* if someone can not decide between more than 2 issues, they should either prefer one that has at least one other person that's willing to work on it, OR we use SIG meetings to discuss which one would be more beneficial for the community.
* after an issue is completed, they can pick a new one. Completed includes "that doesn't work, let's close it/put it on hold, and work on something else"

We can do this async + sync at the same time, e.g. some people will just pick their issues, but some might prefer having a chat during a SIG call and then do the self-assignment during the SIG call

With 6-8 people in this SIG (based on SIG attendence, slack&github activity, names listed on the initial proposal), we would have 4-5 projects max that people work on.

**Comment by tedsuo** [comment]
Sounds great, thanks @svrnm!

**Comment by tedsuo** [comment]
btw, using assignees to green light issues means we can still use 👍 to vote on what we think are important

**Comment by codefromthecrypt** [comment]
Seems to me that we are using assignees because it is more formal than 👍 or technically easier? What I don't like about this is that from an outside pov, it may mean many people are working on it, when really it is more about a voting system. Regardless, sounds fine.

**Comment by codefromthecrypt** [comment]
despite being fine with this and understanding the intent is all good, this does feel like borderline overengineering or overprocess. I think in a natural case, folks with at least approve can decide to move forward issues regardless of the amount of +1, just that their natural bandwidth limits will rate-limit. I do prefer some sort of async thing to avoid meeting lock-ups, but also stepping back this seems process heavy and I wonder if we'll end up spending energy nagging people to assign to something just to fit the process we've added. We'll find out and I'm not afraid to try.

**Comment by svrnm** [comment]
@codefromthecrypt we us the assignees to make sure that we distinguish between "Thumbs up, cool, _somone_ should work on that" and "I assign this to myself, because I will work on that". We could _probably_ work with a single assignee, but I think from the get go it's good to have multiple (suggestion here: 3) work on something.

**Comment by codefromthecrypt** [comment]
from the meeting, I'm much more comfortable with some vocab about this being a stage related concern. Gave a suggestion here https://github.com/open-telemetry/sig-contributor-experience/pull/21/files#r1703743609

**Comment by theletterf** [comment]
I suggest moving this one to Discussions
